# frozen_string_literal: true
source 'https://rubygems.org'

group :test do
  gem 'rake'
  gem 'cucumber'
  gem 'watir-webdriver'
  gem 'rspec-expectations'
  gem 'page-object'
  gem 'test-unit'
  gem 'factory_girl'
  gem 'rest-client'
  gem 'rack-cache'
  gem 'vcr'
  gem 'rspec'
  gem 'webmock'
  gem 'byebug'
  gem 'ci_reporter', git: 'git://github.com/nicksieger/ci_reporter.git'
  gem 'ci_reporter_minitest'
  gem 'minitest-ci', :git => 'git@github.com:circleci/minitest-ci.git'
  gem 'ci'
  gem 'rspec-wait'
  gem 'minitest'
  gem 'rotp'
  gem 'rspec_junit_formatter'
end
